### ISSUE TITLE
[Bug] Minecraft crashes with WilderWild mod installed

### ISSUE THREAD

**Issue by andw20** [Zgoly/Meteorist#30]
### Describe the bug

Minecraft will crash when having Meteorist v1.6 and WilderWild mod installed.

Crash report
[crash-2023-08-03_18.42.13-client.txt](https://github.com/Zgoly/Meteorist/files/12255556/crash-2023-08-03_18.42.13-client.txt)

Latest log
[latest.log](https://github.com/Zgoly/Meteorist/files/12255555/latest.log)

Fabric Loader version
1.20.1 / v0.14.22

Note: I tested this out with ONLY 
1) Baritone v1.10.1
2) Meteor Client 1.20.1 build 1870
3) Meteorist v1.6
4) WilderWild v2.1.1
5) Fabric API 0.86.1

### Steps to reproduce

```bash
1) Download WilderWild mod with Meteor client and Meteorist addon 
2) Start minecraft 
3) Dies
```

### Meteorist Version

1.6

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Zgoly** [comment]
I make a small research and test 3 Meteor addons:
[Meteor Rejects](https://github.com/AntiCope/meteor-rejects)
[Meteor Plus](https://github.com/Nekiplay/MeteorPlus)
[Trouser Streak](https://github.com/etianl/Trouser-Streak)

I tested all addons with these mods:

- Fabric API
- Meteor Client
- Wilder Wild
- (one mod from the list above)

Each of the 3 addons crashed.

In the logs you can see what causes the crash:
https://github.com/AntiCope/meteor-rejects/blob/master/src/main/java/anticope/rejects/MeteorRejectsAddon.java#L87
https://github.com/Nekiplay/MeteorPlus/blob/main/src/main/java/olejka/meteorplus/MeteorPlus.java#L58
https://github.com/etianl/Trouser-Streak/blob/main/src/main/java/pwn/noobs/trouserstreak/Trouser.java#L46

As you can see, all 3 crashes have one thing in common: they are all due to commands that exist in these addons.

And I think you already understand what Meteorist crash is pointing to:
https://github.com/Zgoly/Meteorist/blob/main/src/main/java/zgoly/meteorist/Meteorist.java#L55

This is definitely not the problem with Meteorist. This happens with all addons that have commands. The problem is either Meteor or Wilder Wild itself.

**Comment by Zgoly** [comment]
As for Meteorist version, this is true, but I wonder why version hasn't changed?
In any case, even with the wrong version, all updates from 1.6 are present. I think it's a bug or something like that.

**Comment by Zgoly** [comment]
I don't think things like this are fixable at the moment. Fabric is throwing `Unfixable conflicts` error and I have no idea how to fix it. :(
